version: '3.5'

services:

  server:
    image: completestack:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: completestack
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://JoeRino:azqswxccc@mongo:27017/myFirstDatabase

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: completestack
      DB_USER: completestack
      DB_PASS: completestack
      DB_NAME: completestack

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
